config/routes.rb
Html::Application.routes.draw do
  
  resources :companies do
    member do
      get "people"
    end
    resources :comments
  end
  
  resources :people do
    resources :comments
  end
  
  resources :categories

  resources :users 
  
  resources :tasks do
    resources :items do
      collection do
        post :sort
      end
      member do
        post :export
      end
    end
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  
  match 'register' => 'users#create', :as => :register
  
  match 'login' => 'sessions#new', :as => :login
  
  match 'logout' => 'sessions#destroy', :as => :logout
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/admin/index.html" => "admin#index", :as => :admin
  root :to => "pages/home#index"

end

app/models/person.rb
# -*- encoding : utf-8 -*-
class Person < ActiveRecord::Base
  belongs_to :company
  has_many :comments, :as => :commentable, :dependent => :destroy
  
  validates :name, :presence => true,
                   :uniqueness => {:scope => :company_id, :message => "no puede repetirse dentro de la misma empresa"},
                   :length => {:minimum => 3}
  validates_length_of :title, :allow_blank => true, :minimum => 3
  
  def self.search_people(params)
    condition = []
    value     = {}
    if params[:sname].present?
      condition << "name like :sname"
      value[:sname] = "%#{params[:sname]}%"
    end
    if params[:screated].present?
      condition << "created_at > :screated"
      value[:screated] = params[:screated]
    end
    self.where(condition.join(" AND "), value)
  end
  
end

app/controllers/people_controller.rb
# -*- encoding : utf-8 -*-
class PeopleController < AdminController
  
  before_filter :find_person, :only => [:show, :edit, :update, :people, :destroy]
  before_filter :load_companies, :only => [:new, :create, :edit, :update]
  
  def create
    @person = Person.new(params[:person])

    if @person.save
      redirect_to(people_url, :success => 'Persona creada correctamente')
    else
      render :action => "new"
    end
  end
  
  def destroy
    @person.destroy
    redirect_to(people_url)
  end
  
  def index
    @people = Person.search_people(params).includes(:company).order("name").paginate(:page => (params[:page] || 1))
  end
  
  def new
    @person = Person.new
  end
  
  def show
    @comments = @person.comments.includes(:user).last_comments.paginate(:page => (params[:page] || 1))
  end
  
  def update
    if @person.update_attributes(params[:person])
      redirect_to(@person, :success => 'Persona actualizada correctamente')
    else
      render :action => "edit"
    end
  end
  
  protected
  
  def find_person
    @person = Person.find(params[:id])
  end
  
  def load_companies
    @companies = Company.order("name").all.collect { |c| [c.name, c.id]}
  end
  
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
.row
  .span16
    = error_messages_for :person
    = form_for @person do |p|
      .clearfix
        = p.label :name
        .input
          = p.text_field :name, :class => "xxlarge"
      .clearfix
        = p.label :title
        .input
          = p.text_field :title, :class => "xxlarge"
      .clearfix
        = p.label :company_id
        .input
          = p.select :company_id, @companies, {:include_blank => true}, :class => "xxlarge"    
      .clearfix
        = p.label :twitter
        .input
          = p.text_field :twitter
      .clearfix
        = p.label :linkedin
        .input
          = p.text_field :linkedin, :class => "xxlarge"    
      .clearfix
        = p.label :details
        .input
          = p.text_area :details, :class => "xxlarge", :rows => 5
      .clearfix
        .input
          = p.submit 'Guardar datos', :class => "btn"

app/views/people/_person.html.haml
%tr
  %td
    = link_to person.name, person_url(person)
  %td
    = person.company.present? ? link_to(person.company.name, company_url(person.company)) : "---"
  %td
    = person.title
  %td
    = link_to "Modificar datos", edit_person_url(person), :class => "btn primary"

app/views/people/edit.html.haml
%h1 
  = @person.name
= render 'form'

app/views/people/index.html.haml
%h1
  Listado de personas
  
.row
  .span16
    = form_tag people_url, :method => :get do
      .clearfix
        = label_tag :sname, "Texto a buscar"
        .input
          = text_field_tag :sname
      .clearfix
        = label_tag :screated, "Fecha de alta"
        .input
          = text_field_tag :screated, '', :class => "datepicker"
      .clearfix
        .input
          = submit_tag 'Buscar personas', :class => "btn"
      
  

%table.zebra-striped
  %thead
    %tr
      %th Nombre
      %th Empresa
      %th Cargo
      %th Detalles
  %tbody
    = render :partial => "people/person", :collection => @people
  %tfoot
    %tr
      %td{ :colspan => 3}
        = will_paginate @people

app/views/people/new.html.haml
%h1 Nueva persona
= render 'form'

app/views/people/show.html.haml
%h1.span16 
  = @person.name
.row
  .span16
    = @person.details
.row
  .span16
    %h2 Últimos comentarios realizados
= render :partial => "shared/comment", :collection => @comments
= will_paginate @comments
= render :partial => "shared/new_comment", :locals => {:commenter => @person, :commenter_name => @person.name}

- content_for :sidebar do
  .well
    %p
      = link_to "Nuevo comentario", new_person_comment_url(@person), :class => "btn info", "data-controls-modal" => "modal-from-dom", "data-backdrop" => "true", "data-keyboard" => "true"    