config/routes.rb
Html::Application.routes.draw do
  
  resources :companies do
    member do
      get "people"
    end
    resources :comments
  end
  
  resources :people do
    resources :comments
  end
  
  resources :categories

  resources :users 
  
  resources :tasks do
    resources :items do
      collection do
        post :sort
      end
      member do
        post :export
      end
    end
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  
  match 'register' => 'users#create', :as => :register
  
  match 'login' => 'sessions#new', :as => :login
  
  match 'logout' => 'sessions#destroy', :as => :logout
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/admin/index.html" => "admin#index", :as => :admin
  root :to => "pages/home#index"

end

app/views/shared/_comment.html.haml
.row
  .span3
    = comment.user.name
    %br/
    = comment.created_at.strftime("%d-%m-%y %H:%M")
  .span13
    = comment.details
%hr/    

app/views/shared/_flash_message.html.haml
- if flash.present?
  - flash.each do |status, message|
    %div{:class => ["alert-message fade in", status], "data-alert" => "alert" }
      =link_to("X", "#", :class => "close")
      %p
        %strong
          = message

app/views/shared/_new_comment.html.haml
#modal-from-dom.modal.hide.fade
  .modal-header
    = link_to "x", "#", :class => "close"
    %h3 Nuevo comentario
  .modal-body
    = form_for [commenter, Comment.new], :html => {:class => "form-stacked"} do |com|
      .clearfix
        = com.label :details
        .input
          = com.text_area :details, :class => "xxlarge", :rows => 5, :cols => 50
      .clearfix
        .input
          = com.submit "Guardar comentario", :class => "btn primary"
  .modal-footer
    Comentario para #{commenter_name}

app/views/shared/_new_item.html.haml
#modal-from-dom.modal.hide.fade
  .modal-header
    = link_to "x", "#", :class => "close"
    %h3 Nuevo item
  .modal-body
    = form_for [@task, Item.new], :html => {:class => "form-stacked"} do |com|
      .clearfix
        = com.label :title
        .input
          = com.text_field :title, :class => "xxlarge"
      .clearfix
        .input
          = com.submit "Guardar tarea", :class => "btn primary"
  .modal-footer
    Item para la tarea #{@task.title}

app/views/shared/_sidebar.html.haml
.well
  %h5 Menu lateral
  %p
    = link_to "Nueva empresa", new_company_url, :class => "btn info"
  %p  
    = link_to "Nueva persona", new_person_url, :class => "btn info"    
  %p  
    = link_to "Nueva tarea", new_task_url, :class => "btn info"