config/routes.rb
Html::Application.routes.draw do
  
  resources :companies do
    member do
      get "people"
    end
    resources :comments
  end
  
  resources :people do
    resources :comments
  end
  
  resources :categories

  resources :users 
  
  resources :tasks do
    resources :items do
      collection do
        post :sort
      end
      member do
        post :export
      end
    end
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  
  match 'register' => 'users#create', :as => :register
  
  match 'login' => 'sessions#new', :as => :login
  
  match 'logout' => 'sessions#destroy', :as => :logout
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/admin/index.html" => "admin#index", :as => :admin
  root :to => "pages/home#index"

end

app/models/company.rb
# -*- encoding : utf-8 -*-
class Company < ActiveRecord::Base
  has_many :people, :dependent => :destroy
  has_many :comments, :as => :commentable
  
  validates_presence_of :name
  
  validates_uniqueness_of :name
  
end

app/controllers/companies_controller.rb
# -*- encoding : utf-8 -*-
class CompaniesController < AdminController
  
  before_filter :find_company, :only => [:show, :edit, :update, :people, :destroy]

  def create
    @company = Company.new(params[:company])

    if @company.save
      redirect_to(companies_url, :success => 'Empresa creada correctamente')
    else
      render :action => "new"
    end
  end
  
  def destroy
    @company.destroy
    redirect_to(companies_url)
  end
  
  def edit
    
  end
  
  def index
    @companies = Company.paginate(:page => (params[:page] || 1))
  end
  
  def new
    @company = Company.new
  end
  
  def people
    @people = @company.people.order("name").paginate(:page => (params[:page] || 1))
  end
  
  def show
    @comments = @company.comments.includes(:user).last_comments.paginate(:page => (params[:page] || 1))
  end
  
  def update

    if @company.update_attributes(params[:company])
      redirect_to(@company, :success => 'Compañia actualizada correctamente')
    else
      render :action => "edit"
    end
  end
  
  protected
  
  def find_company
    @company = Company.find(params[:id])
  end
  
end

app/helpers/companies_helper.rb
# -*- encoding : utf-8 -*-
module CompaniesHelper
end

app/views/companies/_company.html.haml
%tr
  %td
    = link_to company.name, company
  %td
    = truncate(company.details, :length => 70)
  %td
    = link_to 'Modificar datos', edit_company_path(company)
  %td
    = link_to 'Destroy', company, :confirm => 'Estás seguro?', :method => :delete, :class => "btn danger"

app/views/companies/_form.html.haml
.row
  .span16
    = error_messages_for :company
    = form_for @company do |c|
      .clearfix
        = c.label :name
        .input
          = c.text_field :name, :class => "xxlarge"
      .clearfix
        = c.label :details
        .input
          = c.text_area :details, :class => "xxlarge", :rows => 5
      .clearfix
        .input
          = c.submit 'Guardar datos', :class => "btn"

app/views/companies/edit.html.haml
%h1 Modificar empresa #{@company.name}
= render 'form'

app/views/companies/index.html.haml
%h1 Empresas

%table.zebra-striped
  %tr
    %th Nombre
    %th Detalles
    %th 
    %th
    %th
  = render @companies

app/views/companies/new.html.haml
%h1 Nueva empresa
= render 'form'

app/views/companies/people.html.haml
%h1
  = @company.name
%h2 Personas relacionadas

%table.zebra-striped
  %thead
    %tr
      %th Nombre
      %th Cargo
      %th Detalles
  %tbody
    - @people.each do |person|
      %tr
        %td
          = link_to person.name, person_url(person)
        %td
          = person.title
        %td
          = link_to "Modificar datos", edit_person_url(person), :class => "btn primary"
  %tfoot
    %tr
      %td{ :colspan => 3}
        = will_paginate @people

app/views/companies/show.html.haml
%h1.span16 
  = @company.name
.row
  .span16
    = @company.details    
.row
  .span16
    %h2 Últimos comentarios realizados
= render :partial => "shared/comment", :collection => @comments
= will_paginate @comments
= render :partial => "shared/new_comment", :locals => {:commenter => @company, :commenter_name => @company.name}

- content_for :sidebar do
  .well
    %p
      = link_to "Personas relacionadas", people_company_url(@company), :class => "btn"
    %p
      = link_to "Nuevo comentario", new_company_comment_url(@company), :class => "btn info", "data-controls-modal" => "modal-from-dom", "data-backdrop" => "true", "data-keyboard" => "true"
    