config/routes.rb
Html::Application.routes.draw do
  
  resources :companies do
    member do
      get "people"
    end
    resources :comments
  end
  
  resources :people do
    resources :comments
  end
  
  resources :categories

  resources :users 
  
  resources :tasks do
    resources :items do
      collection do
        post :sort
      end
      member do
        post :export
      end
    end
    resources :comments
  end

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup
  
  match 'register' => 'users#create', :as => :register
  
  match 'login' => 'sessions#new', :as => :login
  
  match 'logout' => 'sessions#destroy', :as => :logout
  
  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match "/admin/index.html" => "admin#index", :as => :admin
  root :to => "pages/home#index"

end

app/views/layouts/_header.html.haml
%head
  %title  Html
  = stylesheet_link_tag :all
  = javascript_include_tag :defaults, "bootstrap"
  /[if lt IE 9]
    = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
  = csrf_meta_tag

app/views/layouts/_page_footer.html.haml
%footer
  %p
    &copy; Formación Eniac 2011 - Por Jorge Alvarez http://www.alvareznavarro.es - Twitter: @jorgealvarez

app/views/layouts/_page_header.html.haml
%header.topbar
  .topbar-inner
    .container-fluid
      %a.brand{ :href => "#" } CRM on Rails
      %ul.nav
        %li 
          =link_to("Inicio", root_url)
        %li 
          = link_to "Empresas", companies_url
        %li
          = link_to "Personas", people_url
        %li
          = link_to "Tareas", tasks_url
      %ul.nav.secondary-nav
        %li 
          =link_to("Ayuda", "http://google.com")
        %li 
          =link_to("Log out", logout_url)  

app/views/layouts/application.html.haml
!!! 5
%html
  = render :partial => "layouts/header"
  %body
    = render :partial => "layouts/page_header"
    .container-fluid
      .sidebar
        = content_for?(:sidebar) ? yield(:sidebar) : render("shared/sidebar")
      .content
        = render :partial => "shared/flash_message"
        = yield
      = render :partial => "layouts/page_footer"

app/views/layouts/public.html.haml
!!! 5
%html
  = render :partial => "layouts/header"
  %body
    %header.topbar
      .topbar-inner
        .container-fluid
          %a.brand{ :href => "#" } CRM on Rails
    .content
      = render :partial => "shared/flash_message"
      = yield
    %footer
      %p
        &copy; Formación Eniac 2011 - Por Jorge Alvarez http://www.alvareznavarro.es - Twitter: @jorgealvarez